# 122648 - Tiago Lopes

name: Qodana God Class Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          linter: jetbrains/qodana-jvm
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
