# NUMERO_ALUNO - NOME

name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: mvn clean verify

      - name: Run SonarCloud analysis
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
